Repository Donggrina/Backend, pull requests merged in 2024-05, with the labels that each got.

#5 카카오 로그인 구현
  build.gradle.kts
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/java/com/codeit/donggrina/common/util/SecurityUtil.java
  src/main/java/com/codeit/donggrina/domain/member/dto/CustomOAuth2User.java
  src/main/java/com/codeit/donggrina/domain/member/dto/KakaoResponse.java
  src/main/java/com/codeit/donggrina/domain/member/dto/MemberSecurityDto.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtFilter.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtUtil.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
  src/main/resources/application-local.yml
Labels: feat, fix

#4 그룹(가족) 생성 및 그룹별 초대코드 생성
  .github/workflows/deploy.yml
  src/main/java/com/codeit/donggrina/DonggrinaApplication.java
  src/main/java/com/codeit/donggrina/common/Timestamp.java
  src/main/java/com/codeit/donggrina/common/api/ApiControllerAdvice.java
  src/main/java/com/codeit/donggrina/common/api/ApiResponse.java
  src/main/java/com/codeit/donggrina/common/api/ErrorResponse.java
  src/main/java/com/codeit/donggrina/common/api/ValidationErrorResponse.java
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/dto/request/GroupAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/repository/GroupRepository.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: feat

#9 그룹 생성 Refactoring, 그룹 멤버 초대 Feature
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/dto/request/GroupAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/group/dto/request/GroupMemberAddRequest.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/resources/application-local.yml
Labels: feat, refactor

#11 그룹 정보(이름) 수정
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/dto/request/GroupUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: feat

#15 카카오 로그인 리팩토링, redirect 주소 설정
  src/main/java/com/codeit/donggrina/common/util/SecurityUtil.java
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/member/dto/request/CustomOAuth2User.java
  src/main/java/com/codeit/donggrina/domain/member/dto/request/MemberSecurityDto.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/KakaoResponse.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtFilter.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: feat, refactor

#13 사용자 프로필 조회
  .gitignore
  src/main/java/com/codeit/donggrina/domain/ProfileImage/entity/ProfileImage.java
  src/main/java/com/codeit/donggrina/domain/member/controller/MemberController.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/MyProfileGetResponse.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
  src/main/java/com/codeit/donggrina/domain/member/service/MemberService.java
Labels: feat, chore

#16 그룹 삭제 기능 구현, 그룹 생성 버그 수정
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: feat, fix

#19 그룹에서 멤버 삭제, 그룹 삭제 버그 수정
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
Labels: feat, fix

#23 쿠키 오류 수정
  src/main/java/com/codeit/donggrina/common/config/CorsMvcConfig.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: feat

#24 토큰 전달 방식 추가
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: feat

#25 그룹 상세 조회 기능 구현
  src/main/java/com/codeit/donggrina/common/config/QuerydslConfig.java
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/dto/response/GroupDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepository.java
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/group/repository/GroupRepository.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/MyProfileGetResponse.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
Labels: feat

#27 그룹 상세 조회 시 groupId 받는 방식 변경
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: fix

#30 프론트 배포 서버 주소 적용
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#33 cors 설정 수정
  src/main/java/com/codeit/donggrina/common/config/CorsMvcConfig.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#32 대상 그룹 헬스체크용 API 추가
  src/main/java/com/codeit/donggrina/common/HealthCheckController.java
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
Labels: chore

#34 cors 프론트 주소 수정
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
Labels: fix

#35 쿠키 옵션 추가
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: feat

#36 cookie 도메인 수정
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#37 쿠키 설정 방법 변경
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#39 SecurityConfig 수정
  src/main/java/com/codeit/donggrina/common/config/CorsMvcConfig.java
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#41 프론트 redirect url 변경
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#40 펫 추가
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetAddRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Sex.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/SexValueConverter.java
  src/main/java/com/codeit/donggrina/domain/pet/repository/PetRepository.java
Labels: feat

#44 반려동물 리스트 조회
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindListResponse.java
Labels: feat
