Repository Donggrina/Backend, pull requests merged in 2024-06, with the labels that each got.

#45 이미지 업로드 기능
  build.gradle.kts
  src/main/java/com/codeit/donggrina/common/api/ApiControllerAdvice.java
  src/main/java/com/codeit/donggrina/common/config/AsyncConfig.java
  src/main/java/com/codeit/donggrina/common/config/S3Config.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/controller/ProfileImageController.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/entity/ProfileImage.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/exception/ImageUploadException.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/repository/ProfileImageRepository.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/service/ProfileImageService.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/util/S3Uploader.java
  src/main/resources/application-local.yml
Labels: feat, fix

#47 성장 기록 추가
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepository.java
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/GrowthHistoryAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/GrowthHistoryContentDto.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistory.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistoryCategory.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/GrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/util/CategoryEnumConverter.java
Labels: feat

#48 사용자 프로필 수정
  src/main/java/com/codeit/donggrina/domain/member/controller/MemberController.java
  src/main/java/com/codeit/donggrina/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/service/MemberService.java
Labels: feat

#51 카카오 로그인 후 이미지 저장
  src/main/java/com/codeit/donggrina/domain/member/dto/response/KakaoResponse.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
Labels: feat

#55 로그인 후 쿠키 저장 테스트 위해 리디렉션 주소 변경
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#56 쿠키 설정 시 secure, samesite 빼고 만들기(프론트 로컬 개발용)
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#53 성장기록 수정 기능
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/GrowthHistoryUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistory.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
Labels: feat

#57 반려동물 상세 조회
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/pet/controller/PetController.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindResponse.java
  src/main/java/com/codeit/donggrina/domain/pet/repository/PetRepository.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: feat, fix

#60 성장기록 삭제 기능 구현, 성장기록 수정 기능 보강
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#62 리다이렉팅 주소 변경
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#65 성장 기록 상세 조회
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/GrowthHistoryContentDto.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/GrowthHistoryAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/GrowthHistoryUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/GrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#68 성장기록 날짜별 조회
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryListResponse.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#69 반려동물 수정
  src/main/java/com/codeit/donggrina/domain/pet/controller/PetController.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: feat

#71 S3 와 프로필 이미지 데이터베이스 스케줄링 삭제
  src/main/java/com/codeit/donggrina/DonggrinaApplication.java
  src/main/java/com/codeit/donggrina/common/api/ApiControllerAdvice.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/exception/ImageDeleteException.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/repository/CustomProfileImageRepository.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/repository/CustomProfileImageRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/repository/ProfileImageRepository.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/service/ProfileImageService.java
  src/main/java/com/codeit/donggrina/domain/ProfileImage/util/S3Handler.java
Labels: feat

#73 성장기록 검색 기능 구현
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/request/SearchFilter.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistory.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#76 일정 등록
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/CalendarCategory.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/calendar/util/CalendarCategoryEnumConverter.java
  src/main/java/com/codeit/donggrina/domain/calendar/util/IsoDateTime.java
  src/main/java/com/codeit/donggrina/domain/calendar/util/IsoDateTimeValidator.java
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
Labels: feat

#78 일정 수정
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepository.java
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#81 일정 삭제 기능
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
Labels: feat

#79 Feature/#75 add diary
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/request/DiaryCreateRequest.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryImageRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat

#82 다이어리 이미지 저장
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryImageController.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryImageRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryImageService.java
Labels: feat

#86 일정 상세 조회 기능
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
Labels: feat, fix

#84 다이어리 수정
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/request/DiaryUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat

#89 일정 완료 여부 상태 업데이트 기능
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
Labels: feat

#90 다이어리 삭제
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat

#93 일정 전체 조회(월별, 일별)
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarDailyCountResponse.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarListResponse.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
Labels: feat

#97 다이어리 엔티티 수정 및 join 이름 변경
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
Labels: feat, fix

#95 성장기록 날짜별 조회 시 그룹 id 조건 추가, 일정 검색 기능
  src/main/java/com/codeit/donggrina/common/api/SearchFilter.java
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat, fix

#101 불필요한 도커 이미지 삭제
  .github/workflows/deploy.yml
Labels: chore

#104 새로운 멤버 초대 시 사용할 초대코드 조회
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/dto/response/GroupCodeResponse.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: feat

#106 일정의 memo 를 필수 입력 필드로 변경
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarUpdateRequest.java
Labels: fix

#108 fix: CORS 오리진에 localhost:3000 추가
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
Labels: fix

#99 refresh token 적용
  .github/workflows/deploy.yml
  build.gradle.kts
  docker-compose.yml
  src/main/java/com/codeit/donggrina/common/config/RedisConfig.java
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/java/com/codeit/donggrina/domain/member/controller/TokenController.java
  src/main/java/com/codeit/donggrina/domain/member/dto/request/RefreshTokenRequest.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtFilter.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtUtil.java
  src/main/java/com/codeit/donggrina/domain/member/repository/RefreshTokenRedisRepository.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
  src/main/java/com/codeit/donggrina/domain/member/service/TokenService.java
  src/main/resources/application-local.yml
Labels: feat, fix

#111 다이어리 전체 조회
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindListResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
Labels: feat

#113 다이어리 좋아요, 좋아요 취소 기능 구현
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/heart/controller/HeartController.java
  src/main/java/com/codeit/donggrina/domain/heart/entity/Heart.java
  src/main/java/com/codeit/donggrina/domain/heart/repository/HeartRepository.java
  src/main/java/com/codeit/donggrina/domain/heart/service/HeartService.java
Labels: feat

#118 일정을 date 별로 조회할 때 완료여부 추가
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarListResponse.java
Labels: feat

#116 다이어리 상세 조회
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat

#122 로그인 성공 시 엑세스 토큰과 리프레시 토큰을 쿠키로 보내줄 때 덮어 씌어지던 문제 수정
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#123 일정, 성장기록 자기가 쓴 건지 확인하는 필드 추가
  src/main/java/com/codeit/donggrina/domain/calendar/controller/CalendarController.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarListResponse.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/controller/GrowthHistoryController.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryListResponse.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: feat

#125 일정, 성장기록 수정 또는 삭제 시 방장은 모두 가능하도록 변경 + 코드 리팩토링
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
Labels: feat, refactor

#128 엔티티 리팩토링
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetAddRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: fix, refactor

#130 엔티티 리팩토링 - 현준
  src/main/java/com/codeit/donggrina/domain/ProfileImage/entity/ProfileImage.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/calendar/entity/CalendarCategory.java
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistory.java
  src/main/java/com/codeit/donggrina/domain/heart/entity/Heart.java
Labels: feat, refactor

#131 registration 삭제
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindResponse.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/repository/PetRepository.java
Labels: fix

#132 사용자 프로필 기본 이미지 설정
  src/main/java/com/codeit/donggrina/domain/member/dto/response/KakaoResponse.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/resources/application-local.yml
Labels: feat, fix, refactor

#134 DB ddl 속성 변경 적용 겸 헬스체크 컨트롤러 문구 변경
  src/main/java/com/codeit/donggrina/common/HealthCheckController.java
Labels: feat

#135 반려동물 기본 이미지 저장
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetAddRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: feat

#137 Heart 엔티티에 Timestamp 추가
  src/main/java/com/codeit/donggrina/domain/heart/entity/Heart.java
Labels: fix

#115 다이어리 등록 오류 수정
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat, fix

#140 댓글, 대댓글 추가
  src/main/java/com/codeit/donggrina/domain/comment/controller/CommentController.java
  src/main/java/com/codeit/donggrina/domain/comment/dto/request/CommentAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/comment/entity/Comment.java
  src/main/java/com/codeit/donggrina/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/donggrina/domain/comment/service/CommentService.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
Labels: feat

#144 일정 일별 조회 시 반려동물 이름 보이도록 필드 추가
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarListResponse.java
Labels: feat

#146 다이어리 검색
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryController.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/request/DiarySearchRequest.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: feat

#150 스토리 생성
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/story/controller/StoryController.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: feat

#154 fix: DateTime 파싱 하는 방식 수정
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarAppendRequest.java
  src/main/java/com/codeit/donggrina/domain/calendar/dto/request/CalendarUpdateRequest.java
Labels: fix

#148 댓글, 대댓글 삭제 기능
  src/main/java/com/codeit/donggrina/domain/comment/controller/CommentController.java
  src/main/java/com/codeit/donggrina/domain/comment/entity/Comment.java
  src/main/java/com/codeit/donggrina/domain/comment/service/CommentService.java
Labels: feat

#156 반려동물 조회 이미지 추가
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindListResponse.java
Labels: fix

#155 스토리 삭제
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/story/controller/StoryController.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: feat

#158 fix: Long 타입 비교 방식 수정
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#160 fix: 도커파일에서 컨테이너 타임존 명시
  Dockerfile
Labels: fix

#162 다이어리 상세 조회
  src/main/java/com/codeit/donggrina/domain/comment/dto/response/CommentFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/Diary.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/story/controller/StoryController.java
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: feat

#165 스토리 전체 조회
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/story/controller/StoryController.java
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindListPage.java
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindListResponse.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: feat

#169 일정기록, 반려동물 상세조회 API 응답 필드 추가
  src/main/java/com/codeit/donggrina/domain/calendar/dto/response/CalendarDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindResponse.java
Labels: feat

#173 성장기록 리스트 조회 시 내용 보이도록 수정
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryListResponse.java
Labels: feat

#174 다이어리 조회 시 댓글, 좋아요 추가
  src/main/java/com/codeit/donggrina/domain/comment/dto/response/CommentFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindListResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/heart/repository/HeartRepository.java
Labels: feat

#175 다이어리 이미지 저장 로직 수정
  src/main/java/com/codeit/donggrina/domain/diary/controller/DiaryImageController.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
Labels: fix, refactor

#176 다이어리 전체 조회 로직 수정
  src/main/java/com/codeit/donggrina/domain/diary/repository/DiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#178 액세스 토큰 만료 시간 조정
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
Labels: fix

#180 accessToken 만료 시 status 값 수정
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtAuthenticationEntryPoint.java
Labels: fix

#181 refreshToken 재 발급 로직 수정
  src/main/java/com/codeit/donggrina/domain/member/dto/request/RefreshTokenRequest.java
  src/main/java/com/codeit/donggrina/domain/member/repository/RefreshTokenRedisRepository.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
  src/main/java/com/codeit/donggrina/domain/member/service/TokenService.java
Labels: fix

#182 리프레시 토큰 저장 수정
  src/main/java/com/codeit/donggrina/domain/member/repository/RefreshTokenRedisRepository.java
Labels: fix

#179 구글 로그인
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/GoogleResponse.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/KakaoResponse.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/OAuth2Response.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
  src/main/resources/application-local.yml
Labels: feat

#184 성장기록 조회 시 반려동물 이름 보이도록 수정
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryDetailResponse.java
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryListResponse.java
Labels: feat

#185 OAuth2 로그인 redirect url 수정
  src/main/java/com/codeit/donggrina/common/config/SecurityConfig.java
  src/main/resources/application-local.yml
Labels: fix

#187 access 토큰 만료시간 조정
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
  src/main/java/com/codeit/donggrina/domain/member/service/TokenService.java
Labels: fix

#188 사용자 프로필 로직 수정
  src/main/java/com/codeit/donggrina/domain/member/controller/MemberController.java
Labels: fix

#189 고양이, 강아지 기본 이미지 구분
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetAddRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/response/PetFindResponse.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Type.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/TypeValueConverter.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
  src/main/resources/application-local.yml
Labels: feat, fix

#191 예외처리 수정
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/member/service/MemberService.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#193 성장기록 리스트 조회 시 조회하려는 카테고리에 맞게 본문 내용 다르게 보이도록 수정
  src/main/java/com/codeit/donggrina/domain/growth_history/dto/response/GrowthHistoryListResponse.java
Labels: refactor

#197 조회 관련 API 로직에 사용자가 그룹에 소속돼 있는지 검증하는 예외 처리 로직 추가
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: fix

#195 사용자 프로필 업데이트 수정
  src/main/java/com/codeit/donggrina/domain/ProfileImage/entity/ProfileImage.java
  src/main/java/com/codeit/donggrina/domain/member/dto/response/MyProfileGetResponse.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
  src/main/java/com/codeit/donggrina/domain/member/repository/MemberRepository.java
  src/main/java/com/codeit/donggrina/domain/member/service/MemberService.java
Labels: fix

#202 일정 & 성장기록 검색 시 groupId 조건 추가
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/codeit/donggrina/domain/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepository.java
  src/main/java/com/codeit/donggrina/domain/growth_history/repository/CustomGrowthHistoryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: fix

#203 다이어리, 반려동물 예외처리 추가
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: feat

#205 다이어리 검색, 그룹장 로직 수정
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepository.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#206 댓글, 그룹 쓰기 작업에서 사용자 그룹 소속 여부 검증 예외처리 추가
  src/main/java/com/codeit/donggrina/domain/comment/service/CommentService.java
  src/main/java/com/codeit/donggrina/domain/group/controller/GroupController.java
  src/main/java/com/codeit/donggrina/domain/group/service/GroupService.java
Labels: fix, refactor

#208 entryPoint 에러 수정
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtAuthenticationEntryPoint.java
Labels: fix

#207 반려동물 삭제, 수정 로직 수정
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: fix

#210 isMine 이 들어가는 응답에 대해서 방장은 true 로 보이도록 수정
  src/main/java/com/codeit/donggrina/domain/calendar/service/CalendarService.java
  src/main/java/com/codeit/donggrina/domain/growth_history/service/GrowthHistoryService.java
Labels: fix

#212 멤버가 그룹에 추가된 순서대로 그룹 조회했을 때 보이도록 변경
  src/main/java/com/codeit/donggrina/domain/group/repository/CustomGroupRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
Labels: feat

#213 프로필 update 로직 수정
  src/main/java/com/codeit/donggrina/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/codeit/donggrina/domain/member/service/MemberService.java
Labels: fix

#215 Member 엔티티의 leaveGroup 메소드 호출 시 joinGroupAt 필드의 값을 null 로 변경
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
Labels: feat

#218 반려동물 코드 리팩토링
  src/main/java/com/codeit/donggrina/domain/group/entity/Group.java
  src/main/java/com/codeit/donggrina/domain/pet/controller/PetController.java
  src/main/java/com/codeit/donggrina/domain/pet/dto/request/PetAddRequest.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
  src/main/java/com/codeit/donggrina/domain/pet/repository/PetRepository.java
  src/main/java/com/codeit/donggrina/domain/pet/service/PetService.java
Labels: refactor

#219 디폴트 이미지들은 S3에서 삭제하지 않는 방식으로 변경
  src/main/java/com/codeit/donggrina/domain/ProfileImage/service/ProfileImageService.java
Labels: fix

#222 isFamily 여부 쿠키로 보내주기(지금은 임시로 쿼리 파라미터로 보내주는 방식)
  src/main/java/com/codeit/donggrina/domain/member/dto/request/CustomOAuth2User.java
  src/main/java/com/codeit/donggrina/domain/member/dto/request/MemberSecurityDto.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtFilter.java
  src/main/java/com/codeit/donggrina/domain/member/jwt/JwtUtil.java
  src/main/java/com/codeit/donggrina/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/codeit/donggrina/domain/member/service/OAuth2LoginSuccessHandler.java
  src/main/java/com/codeit/donggrina/domain/member/service/TokenService.java
Labels: feat

#220 다이어리 코드 리팩토링
  src/main/java/com/codeit/donggrina/domain/diary/dto/request/DiaryCreateRequest.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryImageService.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: refactor

#224 외래키에 on delete cascade 옵션 추가
  src/main/java/com/codeit/donggrina/domain/calendar/entity/Calendar.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/growth_history/entity/GrowthHistory.java
Labels: fix

#226 feat: 멤버가 그룹에서 강퇴 당했을 때 닉네임을 그룹 탈퇴자로 변경하도록 수정
  src/main/java/com/codeit/donggrina/domain/member/entity/Member.java
Labels: feat

#227 다이어리 조회 시 필요 데이터 추가
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#228 스토리 조회 수정
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindListResponse.java
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#229 스토리 조회 시 본인 것인지 구분
  src/main/java/com/codeit/donggrina/domain/story/dto/response/StoryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#230 좋아요 구분 데이터 추가
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#232 다이어리, 스토리 오류 수정
  src/main/java/com/codeit/donggrina/domain/diary/dto/request/DiarySearchRequest.java
  src/main/java/com/codeit/donggrina/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#234 외래키 제약조건에 삭제 cascade 옵션 주기
  src/main/java/com/codeit/donggrina/domain/comment/entity/Comment.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryImage.java
  src/main/java/com/codeit/donggrina/domain/diary/entity/DiaryPet.java
  src/main/java/com/codeit/donggrina/domain/heart/entity/Heart.java
  src/main/java/com/codeit/donggrina/domain/pet/entity/Pet.java
Labels: fix

#235 스토리 조회 시 이미지 중복 제거
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix

#236 다이어리 상세 조회 id 데이터 추가
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#237 다이어리 업데이트 수정
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#238 다이어리 이미지 조회 예외 메시지 수정
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#239 다이어리 조회 수정
  src/main/java/com/codeit/donggrina/domain/diary/dto/response/DiaryFindResponse.java
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
Labels: fix

#240 댓글 갯수 로직 수정
  src/main/java/com/codeit/donggrina/domain/diary/service/DiaryService.java
  src/main/java/com/codeit/donggrina/domain/story/service/StoryService.java
Labels: fix
